version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: ecommerce_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/yt
    environment:
      - DEBUG=True
      - DB_NAME=ecommerce
      - DB_USER=postgres
      - DB_PASSWORD=4
      - DB_HOST=
      - DB_PORT=

volumes:
  postgres_data:
